namespace GrantManagement.Domain.Enums;

public enum AuditAction
{
    Create,
    Update,
    Delete,
    StatusChange,
    Approve,
    Login,
    // CR2
    ScopeSwitch,
    BreakGlassAccess,
    BreakGlassRevoked,
    BreakGlassExpired,
    OwnerProvisioned,
    OwnerSuspended,
    OwnerReactivated,
    OwnerArchived,
    FoundationCreated,
    FoundationRenamed,
    FoundationArchived,
    FoundationLogoUpdated,
    ScopeViolation,
    FoundationAssignmentCreated,
    FoundationAssignmentRevoked,
    OwnerCodeListTemplateUpdated,
    CodeListTemplateApplied,
    InvitationIssued,
    InvitationAccepted,
    InvitationRevoked,
    InvitationResent,
    InvitationExpired,
    PlatformRoleAssigned,
    PlatformRoleRevoked,
    OwnerRoleAssigned,
    OwnerRoleRevoked,
    FoundationRoleChanged,
    PlatformSettingsUpdated,
    OwnerSettingsUpdated,
    AuditArchived,
    DocumentFilepathMigrated
}
